tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "docker-compose", link: false
brew "git"
brew "imagemagick"
brew "node"
brew "postgresql", restart_service: true
brew "rbenv"
brew "redis"
brew "the_silver_searcher"
brew "heroku/brew/heroku"
cask "docker"
